name: Build-App
on: 
  push:
    paths-ignore: 
    - README.md
    - _site/*
    - ".github/workflows/website.yml"

jobs:
  build-linux:
    name: Build App for Linux x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install Dependencies
        run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get install cmake g++ gcc ninja-build libgtk-3-dev libfuse2 -y --no-install-recommends 
      - name: Build
        run: mkdir -p build; cd build; cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --config release --target install 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name:  FatFileFinder_linux64
          path:  build/Release/*.AppImage

  build-mac:
    name: Build App for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: mkdir -p build; cd build; cmake -G "Xcode" -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --config Release --target install
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FatFileFinder_macOS
          path: build/release/*.app
                
  build-windows:
    name: Build App for Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix: 
        arch: [x64, ARM64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Build
        run: mkdir build; cd build; cmake -A${{ matrix.arch }} -DCMAKE_BUILD_TYPE=Release .. ; cmake --build . --config release --target install
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: FatFileFinder_win${{ matrix.arch }}
          path: build\release\*.exe 
