name: Build-App
on: 
  push:
    paths-ignore: 
    - README.md
    - _site/*
    - ".github/workflows/website.yml"

jobs:
  build-linux:
    name: Build App for Linux x64
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install Dependencies
        run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test && sudo apt-get update && sudo apt-get install cmake g++-8 ninja-build libgtk-3-dev -y --no-install-recommends 
      - name: Build
        run: mkdir -p build; cd build; export CC=/usr/bin/gcc-8; export CXX=/usr/bin/g++-8; cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --config release --target install 
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name:  FatFileFinder_linux64
          path:  build/Release/*.AppImage

  build-mac:
    name: Build App for macOS
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: mkdir -p build; cd build; cmake -G "Xcode" -DCMAKE_BUILD_TYPE=Release .. && cmake --build . --config Release --target install
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: FatFileFinder_macOS
          path: build/release/*.app
                
  build-windows:
    name: Build App for Windows
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build
        run: mkdir build; cd build; cmake -DCMAKE_BUILD_TYPE=Release .. ; cmake --build . --config release --target install
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: FatFileFinder_win64
          path: build\release\*.exe 